[project]
name = "trill-proteins"
version = "1.9.0"
description = "Sandbox for Computational Protein Design"
authors = ["Zachary Martinez <martinez.zacharya@gmail.com>"]
license = "MIT"
channels = ["conda-forge", "pytorch", "nvidia", "bioconda", "dglteam/label/th24_cu124"]
platforms = ["linux-64"]

[tasks]
trill = "python -m trill.trill_main cli"

[dependencies]
python = ">=3.11,<3.12"
accelerate = "*"
ambertools = "*"
ase = "*"
beartype = "*"
biopython = "*"
bokeh = "*"
chardet = "*"
chembl_structure_pipeline = "*"
click = "*"
datasets = "*"
deepspeed = "*"
dm-tree = "*"
e3nn = "*"
evaluate = "*"
fair-esm = "*"
fpocket = "*"
gemmi = "*"
gitpython = "*"
h5py = "*"
hydra-core = "*"
icecream = "*"
ipdb = "*"
jaxtyping = "*"
lifelines = "*"
lightgbm = "*"
llvmlite = "*"
loguru = "*"
matplotlib = "*"
mdanalysis = "*"
meeko = "*"
ml-collections = "*"
modelcif = "*"
numba = "*"
numpy = "*"
omegaconf = "*"
openbabel = "*"
openff-toolkit ="*" 
openmm = "*"
openmmforcefields = "*"
optuna = "*"
pandera = "*"
pandas = "*"
pdbfixer = "*"
plotly = "*"
pydantic = "*"
pyfiglet = "*"
pytest = "*"
pytorch-lightning = "*"
rdkit = "*"
scikit-learn = "*"
scikit-optimize = "*"
seaborn = "*"
selfies = "*"
sentencepiece = "*"
setuptools = ">=80.9.0,<81"
skops = "*"
spyrmsd = "*"
smina = "*"
swig = "*"
tensorboard = "*"
tensorboardx = "*"
torch-nl = "*"
transformers = "*"
typed-argument-parser = "*"
umap-learn = "*"
urllib3 = "*"
vina = "*"
xgboost = "*"
dgl = ">=2.3.0,<3"
compilers = ">=1.10.0,<2"
foldseek = ">=10.941cd33,<11"
pyrsistent = ">=0.20.0,<0.21"
pytorch = ">=2.3.1,<3"
torchvision = ">=0.18.1,<0.19"
typer = ">=0.16.0,<0.17"
flash-attn = ">=2.6.1,<3"
triton = ">=3.3.1,<4"

[system-requirements]
cuda = "12"

[tool.pixi.pypi]
pip-extra-index-urls = [
    "https://data.pyg.org/whl/torch-2.7.0+cu121.html"
]

[pypi-dependencies]
antipickle = ">=0.2.0, <0.3"
biobb-vs = ">=5.1.0, <6"
calm = { git = "https://github.com/martinez-zacharya/CaLM.git" }
cuequivariance-ops-cu12 = ">=0.5.1, <0.6"
cuequivariance-ops-torch-cu12 = ">=0.5.1, <0.6"
cuequivariance-torch = ">=0.5.1, <0.6"
ecpick = { git = "https://github.com/martinez-zacharya/ECPICK.git" }
fairscale = ">=0.4.13, <0.5"
fuse-med-ml = ">=0.4.0, <0.5"
lightdock = { git = "https://github.com/martinez-zacharya/lightdock.git", rev = "03a8bc4888c0ff8c98b7f0df4b3c671e3dbf3b1f" }
prolif = { git = "https://github.com/chemosim-lab/ProLIF.git" }
reprint = ">=0.6.0, <0.7"
rna-fm = ">=0.2.2, <0.3"
scasa = { git = "https://github.com/martinez-zacharya/SCASA.git" }
torch-cluster = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu126/torch_cluster-1.6.3%2Bpt27cu126-cp311-cp311-linux_x86_64.whl" }
pyg-lib = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu126/pyg_lib-0.4.0%2Bpt27cu126-cp311-cp311-linux_x86_64.whl" }
#torch-scatter = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu126/torch_scatter-2.1.2%2Bpt27cu126-cp311-cp311-linux_x86_64.whl" }
torch-sparse = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu126/torch_sparse-0.6.18%2Bpt27cu126-cp311-cp311-linux_x86_64.whl" }
torch-spline-conv = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu126/torch_spline_conv-1.2.2%2Bpt27cu126-cp311-cp311-linux_x86_64.whl" }
biotite = "*"

