[project]
name = "trill-proteins"
version = "1.9.0"
description = "Sandbox for Computational Protein Design"
authors = ["Zachary Martinez <martinez.zacharya@gmail.com>"]
license = "MIT"
channels = ["conda-forge", "pytorch", "nvidia", "bioconda"]
platforms = ["linux-64"]

[tasks]
start = "python -m trill.trill_main"

[dependencies]
python = ">=3.11,<3.12"
accelerate = "*"
ambertools = "*"
ase = "*"
beartype = "*"
biopython = "*"
biotite = "*"
bokeh = "*"
chardet = "*"
chembl_structure_pipeline = "*"
click = "*"
datasets = "*"
deepspeed = "*"
dm-tree = "*"
e3nn = "*"
evaluate = "*"
fair-esm = "*"
fpocket = "*"
gemmi = "*"
gitpython = "*"
h5py = "*"
hydra-core = "*"
icecream = "*"
ipdb = "*"
jaxtyping = "*"
lifelines = "*"
lightgbm = "*"
llvmlite = "*"
loguru = "*"
matplotlib = "*"
mdanalysis = "*"
meeko = "*"
ml-collections = "*"
modelcif = "*"
numba = "*"
numpy = "*"
omegaconf = "*"
openbabel = "*"
openff-toolkit ="*" 
openmm = "*"
openmmforcefields = "*"
optuna = "*"
pandera = "*"
pandas = "*"
pdbfixer = "*"
plotly = "*"
pydantic = "*"
pyfiglet = "*"
pytest = "*"
pytorch-lightning = "*"
rdkit = "*"
scikit-learn = "*"
scikit-optimize = "*"
seaborn = "*"
selfies = "*"
sentencepiece = "*"
setuptools = ">=80.9.0,<81"
skops = "*"
spyrmsd = "*"
smina = "*"
swig = "*"
tensorboard = "*"
tensorboardx = "*"
torch-nl = "*"
transformers = "*"
typed-argument-parser = "*"
umap-learn = "*"
urllib3 = "*"
vina = "*"
xgboost = "*"

[system-requirements]
cuda = "12"

[pypi-dependencies]
antipickle = ">=0.2.0, <0.3"
biobb-vs = ">=5.1.0, <6"
cuequivariance-ops-cu12 = ">=0.5.1, <0.6"
cuequivariance-ops-torch-cu12 = ">=0.5.1, <0.6"
cuequivariance-torch = ">=0.5.1, <0.6"
fuse-med-ml = ">=0.4.0, <0.5"
reprint = ">=0.6.0, <0.7"
fairscale = ">=0.4.13, <0.5"
scasa = { git = "https://github.com/martinez-zacharya/SCASA.git" }
lightdock = { git = "https://github.com/martinez-zacharya/lightdock.git", rev = "03a8bc4888c0ff8c98b7f0df4b3c671e3dbf3b1f" }
calm = { git = "https://github.com/martinez-zacharya/CaLM.git" }
ecpick = { git = "https://github.com/martinez-zacharya/ECPICK.git" }
prolif = { git = "https://github.com/chemosim-lab/ProLIF.git" }
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiTRUE-cp311-cp311-linux_x86_64.whl" }
rna-fm = ">=0.2.2, <0.3"
torch-geometric = "*"

